services:
  thumbnail-api:
    build: .
    image: thumbnail:latest
    ports:
      - "4526:4526"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      internal_shared:
        aliases:
          - thumbnail-api
      default: {}

networks:
  internal_shared:
    external: true
    name: internal_shared