services:
  thumbnail-api:
    build: .
    image: thumbnail:latest
    ports:
      - "4526:4526"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./output:/app/output
    networks:
      internal_shared:
        aliases:
          - thumbnail-api
      default: {}

networks:
  internal_shared:
    external: true
    name: internal_shared